### ISSUE TITLE
Not able to compile. Pods-Alamofire Problem 

### ISSUE THREAD

**Issue by cduguet** [huyouare/SwiftParseChat#4]
using ruby-2.0.0 ,  cocoapods 0.37.1

I am installing it using the normal `<pod install>` command. No errors or warnings during the process. 
However, when compiling, I get: 

`No such Module 'Alamofire'`

If I install Alamofire manually, however, when compiling I get an `Apple Match-O Linker` Error :  

```
ld: warning: directory not found for option '-F/Users/cristian/Library/Developer/Xcode/DerivedData/SwiftParseChat-btvjczpwjlekftetblbfrbposakh/Build/Products/Debug-iphoneos/Pods'
ld: framework not found Pods
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

What is behind this?? 

Thanks !

**Comment by michaelbina** [comment]
I'm having the same problem.  Did you ever find a solution?

**Comment by sidpagariya** [comment]
Same problem. Can't fix it. I tried, but still working on the fix.

**Comment by andy-io** [comment]
I am also having the same problem. Did someone find a solution ?

**Comment by John-Connolly** [comment]
When I opened the project everything worked correctly when I followed the readMe.  Make sure that you are opening the X-Code workspace file and not the xcode.proj.  Hope this helps!

**Comment by cduguet** [comment]
the project works correctly. You have to execute the  new X-Code workspace file.
